# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pharaoh/Projekte/FPGA/Xilinx/PmodENC/PmodENC.cache/wt [current_project]
set_property parent.project_path /home/pharaoh/Projekte/FPGA/Xilinx/PmodENC/PmodENC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_repo_paths /home/pharaoh/Projekte/FPGA/Xilinx/IP [current_project]
set_property ip_output_repo /home/pharaoh/Projekte/FPGA/Xilinx/PmodENC/PmodENC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/pharaoh/Projekte/FPGA/FPGAs_fuer_Maker/debounce/debounce.srcs/sources_1/new/debounce.vhd
  /home/pharaoh/Projekte/FPGA/Xilinx/PmodENC/PmodENC.srcs/sources_1/new/rotaryencoder.vhd
  /home/pharaoh/Projekte/FPGA/Xilinx/PmodENC/PmodENC.srcs/sources_1/new/PmodENC.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top PmodENC -part xc7z020clg484-1


write_checkpoint -force -noxdef PmodENC.dcp

catch { report_utilization -file PmodENC_utilization_synth.rpt -pb PmodENC_utilization_synth.pb }
